name: Build ISO

on: push

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          pacman --noconfirm -Syyu
          pacman --noconfirm -S archiso base-devel

      - name: Get AUR packages
        run: bash ./get_aur_pkg.sh

      - name: Build rootfs & ISO
        run: mkarchiso -v .

      - uses: actions/upload-artifact@master
        with:
          name: archiso
          path: out/*.iso
